#!/bin/bash
# This script does what it's written here:
# https://groups.google.com/d/msg/sage-devel/k8IwG8qJPCc/ekDtlhj9hhMJ
# WARNING! Not succesfully tested yet

SAGE_VER=5.0
SAGE_ROOT=/opt/sage-5.0

cd $SAGE_ROOT/devel/
git clone git@github.com:samuela/sagenb sagenb-github

mv sagenb sagenb-old_UI
ln -s sagenb-github sagenb

cd $SAGE_ROOT/devel/sagenb
../../sage -python setup.py install

ln -s $SAGE_ROOT/devel/sagenb-github /opt/nb-newui
