#!/bin/bash
JULIA_DIR=/opt/julia

help(){
echo "usage: julia-update pkg|clean"
exit 1
}

clean(){
echo "Cleaning julia compiled file."
echo "Run julia-update again to rebuild"
cd $JULIA_DIR
make clean
exit 0
}

update_packages(){
echo "Updating julia packages"
julia -e "Pkg.update()"
exit 0
}

update_julia(){
echo "Updating julia"
cd $JULIA_DIR
git pull
make -j3 # Leave 1 proc to me
exit 0
}

case $1 in
  ""      ) update_julia;;
  "pkg"   ) update_packages;;
  "clean" ) clean;;
  * ) help;;
esac