#!/bin/bash
JULIA_DIR=/opt/julia

help(){
echo "usage: julia-update pkg|all|clean"
exit 1
}

clean_update(){
echo "Cleaning julia compiled file."
cd $JULIA_DIR
make clean
update_julia
exit 0
}

update_packages(){
echo "Updating julia packages"
julia -e "Pkg.update()"
exit 0
}

update_julia(){
echo "Updating julia"
cd $JULIA_DIR
git pull
make -j3 # Leave 1 proc to me
exit 0
}

all(){
clean_update
update_julia
update_packages
}
case $1 in
  ""      ) update_julia;;
  "all"   ) all;;
  "pkg"   ) update_packages;;
  "clean" ) clean_update;;
  * ) help;;
esac
