#!/bin/bash

# Wanted usage:
#	libretto -s=<scala> -p=<formato pagina> input_file.pdf output_file.pdf
#
# TODO:
#  - preparare un parametro if a seconda della dimensione del foglio
#  - accomodare i diversi parametri -s, -p input e output.

pdftops $1 output.ps
scala=1.1
# dimensioni in cm del foglio A4 210mm×297mm
A4_width=21
A4_heigth=29.7
# dimensioni in cm del foglio US letter 215.9mm×279.4mm
USletter_width=21.59
USletter_heigth=27.94

sposta_sx=`echo "(1-$scala)/2*$USletter_width" | bc -l`; echo $sposta_sx
sposta_giu=`echo "(1-$scala)/2*$USletter_heigth" | bc -l`; echo $sposta_giu

#riscalatura (in pratica rimuove i margini) e centra la pagina
pstops -pletter "@$scala(${sposta_sx}cm,${sposta_giu}cm)" output.ps output_riscalato.ps
ps2pdf -sPAPERSIZE=letter output_riscalato.ps ${1%.*}_riscalato.pdf
rm output_riscalato.ps

#fa il libretto
# output_name=${1%.*}_libretto.pdf
# psbook output.ps tmp.ps
# psnup -pA4 -2 tmp.ps booklet.ps
# rm output.ps tmp.ps
# ps2pdf booklet.ps $output_name
# rm booklet.ps
# okular $output_name