#!/bin/bash
# Removes old revisions of snaps
# CLOSE ALL SNAPS BEFORE RUNNING THIS

# from https://superuser.com/a/1330590

set -eu
sudo -v

snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
    	# echo "$snapname$revision"
        sudo snap remove "$snapname" --revision="$revision"
    done