#!/bin/bash
# usage: ./scale in.pdf out.pdf
# Scala il file di ingresso del 90 percento e centra le pagine
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dSAFER \
  -dCompatibilityLevel="1.3" -dPDFSETTINGS="/printer" \
  -dSubsetFonts=true -dEmbedAllFonts=true \
  -sPAPERSIZE=a4 -sOutputFile="$2" \
  -c "<</BeginPage{0.9 0.9 scale 29.75 42.1 translate}>> \
  setpagedevice" \
  -f "$1"
