#!/bin/bash
# Michele Mastropietro
# Thanks to Unix.stackexchange user Graeme
# http://unix.stackexchange.com/a/210992/29264

usage(){
    echo "usage:" 
    echo "       tre-net <interface> [up|down|show-iface]"
    echo "       tre-net test"
    exit 1
}

run_test(){
#   tre curl http://ipecho.net/plain; echo  
    #PINGDEF=`tre curl http://ipecho.net/plain; echo`
    PINGDEF=`sudo ip netns exec tre_ns curl -s http://ipecho.net/plain`
    PINGIFACE=`curl -s http://ipecho.net/plain`
    echo "default interface ip: $PINGDEF"
    echo "tre_ns  interface ip: $PINGIFACE"
    exit 0
}

if [ "$1" = "test" ]; then
    run_test
fi

if [ $# -lt 2 ]; then
    #echo "Number of arguments: $#"
    echo "Incorrect number of arguments"
    usage
fi

sudo echo -n

IFACE=$1

#show-iface() {`ip ro` }

up(){
    echo "--- Creating a network namespace called tre_ns"
    #ip ro

    # Add a new namespace called tre_ns
    sudo ip netns add tre_ns

    # Set test to use IFACE, after this point IFACE is not usable by 
    # programs outside the namespace
    sudo ip link set $IFACE netns tre_ns

    # Bring up IFACE inside tre_ns
    sudo ip netns exec tre_ns ip link set $IFACE up

    # Use dhcp to get an ipv4 address for tre_ns
    sudo ip netns exec tre_ns dhclient $IFACE

    #alias tre_ns="sudo ip netns exec tre_ns"

    echo "--- You can use the new namespace:"
    echo "    $ sudo ip netns exec tre_ns <command>"
    
    exit 0
}

down(){
    echo "--- Deleting network namespace tre_ns"
    echo "--- To be implemented"
    exit 0
}

case $2 in
  "up"   ) up;;
  "down" ) down;;
  "test" ) run_test;;
  "show-iface" ) `ip ro`;; 
  * ) usage;;
esac