#!/bin/bash
sudo -v

echo "---- Old resolv.conf"
cat /etc/resolv.conf

echo "---- Running sed"

sudo sed -i -e 's/ UGent.be//g' /etc/resolv.conf

echo "---- New resolv.conf"
cat /etc/resolv.conf

echo "---- Restarting networking"

sudo service networking restart
